language: node_js
node_js:
  - '8'
  - '10'
  - '11'
  - '12'
before_script:
  - npm ci
script:
  - npm test
  - npm run codecov
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: $NPM_EMAIL
  on:
    tags: true
