name: Test Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install and Validate
        run: |
          yarn install --immutable
          yarn run build
          yarn run eslint
          yarn run test

      - name: Codecov
        run: yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
