name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install and Validate
        run: |
          npm install
          npm run eslint
          npm run test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: |
          npm install

      - name: Setup .yarnrc.yml
        run: |
          npm config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          npm config set npmAlwaysAuth true

      - name: Build
        run: npm run build

      - name: Publish
        run: cd dist && npm publish
